### PR TITLE
Fix permissions of files created by Docker

### PR DESCRIPTION
**Pull request by monosans**
Closes https://github.com/wemake-services/wemake-django-template/issues/1518.

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Thank you, please update docker docs as well?

**Comment by monosans** [comment]
> please update docker docs as well?

It is already kinda documented. See https://wemake-django-template.readthedocs.io/en/latest/pages/template/troubleshooting.html?highlight=docker#root-owns-build-artifacts.

**Comment by monosans** [comment]
> We also need to document `UID` and `GID`

I don't quite understand what exactly needs to be documented. All manipulations with `UID` and `GID` are done automatically and do not require any user intervention.

**Comment by monosans** [comment]
So, all good for the merge?

**Review by sobolevn — APPROVED** [review]
Yes, but please fix https://github.com/wemake-services/wemake-django-template/runs/7132163748?check_suite_focus=true

**Comment by monosans** [comment]
@sobolevn, done.

**Review by sobolevn — APPROVED** [review]
Thanks

**Pull request merged**
