### PR TITLE
Change static folder of main app

### PR DESCRIPTION
**Pull request by DmytroLitvinov**

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Related to https://github.com/wemake-services/wemake-django-template/pull/760 's comment from @sobolevn

**Comment by sobolevn** [comment]
😢 What's wrong with Travis?

**Comment by DmytroLitvinov** [comment]
:anguished:

**Comment by DmytroLitvinov** [comment]
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by DmytroLitvinov** [comment]
https://github.com/sdispater/poetry/issues/476#issuecomment-481825656

**Comment by DmytroLitvinov** [comment]
https://github.com/pypa/warehouse/issues/5583

**Comment by DmytroLitvinov** [comment]
This PR is ready to be merged, @sobolevn 

P.S. do not forget about squashing

**Pull request merged**
