### PR TITLE
Upgrade minor django version

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
On May 1, django announced 1.11.13 version:
https://docs.djangoproject.com/en/2.0/releases/1.11.13/

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
@sobolevn

**Comment by sobolevn** [comment]
@DmytroLitvinov thanks! 
Do you like our setup? Any feedback is highly appreciated. 

P.S. You took @dependabot-bot's job! 😄

**Comment by DmytroLitvinov** [comment]
Ah... I forgot about @dependabot-bot :sweat_smile:

I am trying to use your template for my pet-project.
Is it okay, if I will ping about some improvement or misunderstanding from docs?

**Comment by sobolevn** [comment]
Sure! That's what I encourage people to do.

**Comment by DmytroLitvinov** [comment]
I watched your talk and I am interested in it.
Because at our work we are now facing a problem with the main template for all projects.
And I like your idea. In the future, this will allow of any developer without pain integrate to different project based on one template.

**Pull request merged**
