### PR TITLE
Fix favicon file name and path

### PR DESCRIPTION
**Pull request by wwarne**
With previous images path **ManifestStaticFilesStorage** was failing with an error:
`ValueError: Missing staticfiles manifest entry for '/images/favicon-16x16.png'`.

### CODE REVIEW

**Comment by sobolevn** [comment]
@wwarne thanks! I will merge it shortly after fixing the CI. There's something wrong with `travis` itself.

**Comment by sobolevn** [comment]
@wwarne please rebase your branch. I have fixed the CI.

**Comment by wwarne** [comment]
> @wwarne please rebase your branch. I have fixed the CI.

I'm not sure I did it the right way because I have no experience with rebase, unfortunately.
Can you take a look at this and check if it is ok?.
I can make new pull request in case I failed with good rebase. Sorry for inconvenience.

**Comment by sobolevn** [comment]
@wwarne yes, let's better do a new PR. You have merged my commits.

But, no worries, everything is fine. That's open-source development where you can work just for you own pleasure.

**Pull request closed without merging**
