### PR TITLE
Upgrade poetry version to 0.12.15

### LINKED ISSUE #755: Upgrade poetry to 0.12.15
https://github.com/sdispater/poetry/releases/tag/0.12.15

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Closes #755

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
45 minutes and CI is still building...

**Comment by sobolevn** [comment]
@DmytroLitvinov any luck?

**Comment by DmytroLitvinov** [comment]
No :(

**Comment by DmytroLitvinov** [comment]
This PR is ready to be merged, @sobolevn

**Pull request merged**
