### PR TITLE
Fix flake8 linting

### PR DESCRIPTION
**Pull request by DmytroLitvinov**

### CODE REVIEW

**Comment by sobolevn** [comment]
Something is still failing 😞

**Comment by DmytroLitvinov** [comment]
Hello @sobolevn ,

The main problem with next [lines](https://github.com/wemake-services/wemake-django-template/blob/82069652ea7f1e4e1fd61fa3e2e8baf3aa54e1a2/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/environments/development.py#L22). Here we have next error:

> ./server/settings/environments/development.py:25:1: S104 Possible binding to all interfaces.

More [detail](https://github.com/PyCQA/bandit/blob/master/bandit/plugins/general_bind_all_interfaces.py) about this error:

> Binding to all network interfaces can potentially open up a service to traffic on unintended interfaces, that may not be properly documented or secured. This plugin test looks for a string pattern “0.0.0.0” that may indicate a hardcoded binding to all network interfaces.

Do you have any thoughts on how we can resolve it? I see adding `0.0.0.0` is related to issue #692

**Comment by DmytroLitvinov** [comment]
Also, do we need to lint with flake8 the main repo, not only template?

**Comment by sobolevn** [comment]
@DmytroLitvinov yeap, lint everything! 🙊

**Comment by DmytroLitvinov** [comment]
This MR is ready.
Please review one more time before squashing and merging, @sobolevn .

**Comment by sobolevn** [comment]
@DmytroLitvinov I am not sure what is wrong with the CI.

**Comment by DmytroLitvinov** [comment]
Installing takes a lot of time.. I don't know why it downloads slowly. Did this problem exist before?

**Comment by sobolevn** [comment]
@DmytroLitvinov nope. It is unrelate to this change. And work perfectly locally.
Let's merge it without CI.

**Pull request merged**
