### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by Arfey**
attempt to make docker-compose more friendly for mac os :)
https://docs.docker.com/docker-for-mac/osxfs-caching/

### CODE REVIEW

**Comment by Arfey** [comment]
In my case it's only for develop mode. Mac OS have problem with performance when we talk about volumes and docker. After using this feature reloading after change source code is much quickly then without. So, in develop mode it's good option without any risks.

**Comment by sobolevn** [comment]
@Arfey this change also touches production mode. How reliable is that?

**Comment by Arfey** [comment]
Sorry, you are right. This option use in final `docker-compose.deploy.yml`. I didn't use this option in production, but it's not look as so dangerous.
In any case it's your repo :)

**Comment by DmytroLitvinov** [comment]
It would be nice to have "Tips & tricks" section or something like "Helpful links" where we can add a link to this improving. What do you think, @sobolevn?

**Comment by sobolevn** [comment]
Yes, agreed. I would say that this tip belongs to the docs.
We can mention that this is a nice way to improve your performance locally.
But, we need to clearly describe a problem. What kind of performance? Disk? Network? 
How to notice that your current workflow is slow? Etc.

@Arfey would you please this PR to do it? 
@DmytroLitvinov thanks for the idea! I have never heard of this option, I hope that other our users will find it useful.

**Comment by Arfey** [comment]
Ok maybe a little later.

**Pull request closed without merging**
